import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ja">
      <body className="bg-gray-100 min-h-screen flex flex-col">
        {/* ナビバー */}
        <header className="bg-white border-b border-gray-200 px-6 py-3 flex justify-between items-center sticky top-0 z-10">
          <h1 className="font-bold text-lg text-gray-900">
            ShukatsuTracker
          </h1>

          <nav className="space-x-4">
            <Link href="/" className="text-gray-700 font-medium hover:text-blue-600">
              企業管理
            </Link>
            <Link href="/schedule" className="text-blue-500 hover:underline">
              スケジュール
            </Link>
          </nav>
        </header>
        {/* ページ本体 */}
        <main className="flex-1 p-4 md:p-6">{children}</main>
      </body>
    </html>
  );
}

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};